# Basic Settings
title: dario.com • Tirez parti de vos investissements en confidentialité • Développez votre entreprise
description: Nous optimisons vos programmes de confidentialité et de conformité des données, augmentant la confiance en votre entreprise et les opportunités de croissances.
author: dario
# Language format language_TERRITORY. Default is en_US
lang: fr_CA
# website logos, images & icons
logo: img/chklst.png
image: img/header.jpg
# urls
url: "https://dario.com"
english_url: https://dario.com/
french_url: https://dario.com/fr
baseurl: "/fr"
# resources_url: 'resources'
# services_url: 'services'

# copyright text in footer
copyright: dario.pw

# email address
email: contact@dario.com
email_username: contact@dario.com
# email address in privacy policy
email_privacy: privacy@dario.com

# contact telephone number
telephone_number:

# search tracking id for dario.com
google_tracking_id: UA-98131817-2

webmaster_verifications:
  google: DQehZZh2Dx2G-CEfmIed3hixR8DokYqvKiJwWcn5IiM
  bing: AC24F3DF5CA3A5221FB7E01EF2D9AAC4
  alexa:
  yandex:
  baidu:

# Social/SEO
twitter_username: darioS3C
github_username:
facebook_username:

twitter:
  username: darioS3C

facebook:
  app_id:
  publisher:
  admins:

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]

# gems
gems:
  - jekyll-seo-tag
 
# Build settings
markdown: kramdown
